#!/bin/bash
source /etc/clara.sh
free=$(free -mt | grep Total | awk '{print $4}')
if [[ "$free" -le 1000  ]]; then
echo -e "Warning, server memory is running low!\n\nFree memory: $free MB" | mutt -s "HIGH MEMORY ALERT!!!" $email
fi
