#!/bin/sh
source config.sh
config=`date '+%Y-%m-%d_%H-%M-%S'`.zip
zip -r $config /var/www
md5=$config

echo """
hi
i'm clara. a server Manager bot
this is the Backup for your all websites
file md5:
$md5
"""|mutt -a $config -s "Backup for all your websites"`date '+%Y-%m-%d_%H-%M-%S'` -- $email
rm $config
